#!/bin/bash

## Enable extended globbing features
shopt -s extglob

# Get version number from version tag
JAR_VERSION=`echo $1 | cut -d'v' -f2`

# Set new library version in pom.xml using mvn versions:set command
# These new pom.xml and changelog.md generated by @semantic-release/changelog
# will be commit it by @semantic-release/git
mvn versions:set -DnewVersion=$JAR_VERSION &&

# Package the new library version and copy it to release folder
# These files will be upload to github by @semantic-release/github
mvn -B deploy -DskipTests &&
mkdir release && 
cp target/!(*-sources|*-javadoc).jar release